# nautilus-indicators — technical indicators library.

load("@nt_bazel_defs//rust:defs.bzl", "nt_rust_library", "nt_rust_test")

package(default_visibility = ["//visibility:public"])

nt_rust_test(
    name = "nautilus_indicators_test",
    crate = ":nautilus_indicators",
    edition = "2024",
    deps = ["@nt_crates//:rstest"],
)

nt_rust_library(
    name = "nautilus_indicators",
    srcs = glob(["src/**/*.rs"]),
    crate_name = "nautilus_indicators",
    edition = "2024",
    deps = [
        "//crates/core:nautilus_core",
        "//crates/model:nautilus_model",
        "@nt_crates//:anyhow",
        "@nt_crates//:arraydeque",
        "@nt_crates//:strum",
    ],
)
