# nautilus-analysis — performance stats / analysis helpers.

load("@nt_bazel_defs//rust:defs.bzl", "nt_rust_library", "nt_rust_test")

package(default_visibility = ["//visibility:public"])

nt_rust_test(
    name = "nautilus_analysis_test",
    crate = ":nautilus_analysis",
    edition = "2024",
    deps = ["@nt_crates//:rstest"],
)

nt_rust_library(
    name = "nautilus_analysis",
    srcs = glob(["src/**/*.rs"]),
    crate_name = "nautilus_analysis",
    edition = "2024",
    deps = [
        "//crates/core:nautilus_core",
        "//crates/model:nautilus_model",
        "@nt_crates//:ahash",
        "@nt_crates//:anyhow",
        "@nt_crates//:rust_decimal",
    ],
)
