# nautilus-serialization — SBE / Arrow serialization for the domain model.

load("@nt_bazel_defs//rust:defs.bzl", "nt_rust_library", "nt_rust_test")

package(default_visibility = ["//visibility:public"])

nt_rust_test(
    name = "nautilus_serialization_test",
    crate = ":nautilus_serialization",
    crate_features = [
        "arrow",
        "high-precision",
        "sbe",
    ],
    edition = "2024",
    proc_macro_deps = ["@nt_crates//:rust_decimal_macros"],
    deps = [
        "@nt_crates//:pretty_assertions",
        "@nt_crates//:rstest",
    ],
)

nt_rust_library(
    name = "nautilus_serialization",
    srcs = glob(["src/**/*.rs"]),
    crate_features = [
        "arrow",
        "high-precision",
        "sbe",
    ],
    crate_name = "nautilus_serialization",
    edition = "2024",
    proc_macro_deps = [
        "@nt_crates//:rust_decimal_macros",
    ],
    deps = [
        "//crates/core:nautilus_core",
        "//crates/model:nautilus_model",
        "@nt_crates//:anyhow",
        "@nt_crates//:arrow",
        "@nt_crates//:indexmap",
        "@nt_crates//:rust_decimal",
        "@nt_crates//:serde",
        "@nt_crates//:serde_json",
        "@nt_crates//:thiserror",
        "@nt_crates//:ustr",
        "@nt_crates//:uuid",
    ],
)
