# nautilus-cryptography — crypto primitives.

load("@nt_bazel_defs//rust:defs.bzl", "nt_rust_library", "nt_rust_test")

package(default_visibility = ["//visibility:public"])

nt_rust_test(
    name = "nautilus_cryptography_test",
    crate = ":nautilus_cryptography",
    edition = "2024",
    deps = ["@nt_crates//:rstest"],
)

nt_rust_library(
    name = "nautilus_cryptography",
    srcs = glob(["src/**/*.rs"]),
    crate_name = "nautilus_cryptography",
    edition = "2024",
    deps = [
        "//crates/core:nautilus_core",
        "@nt_crates//:anyhow",
        "@nt_crates//:aws-lc-rs",
        "@nt_crates//:base64",
        "@nt_crates//:ed25519-dalek",
        "@nt_crates//:log",
        "@nt_crates//:pem",
        "@nt_crates//:rustls",
        "@nt_crates//:webpki-roots",
    ],
)
