# nautilus-backtest — historical backtesting engine.

load("@nt_bazel_defs//rust:defs.bzl", "nt_rust_library", "nt_rust_test")

package(default_visibility = ["//visibility:public"])

nt_rust_test(
    name = "nautilus_backtest_test",
    crate = ":nautilus_backtest",
    crate_features = [
        "high-precision",
        "streaming",
    ],
    edition = "2024",
    deps = [
        "//crates/indicators:nautilus_indicators",
        "//crates/persistence:nautilus_persistence",
        "//crates/testkit:nautilus_testkit",
        "//crates/trading:nautilus_trading",
        "@nt_crates//:rstest",
        "@nt_crates//:tempfile",
    ],
)

nt_rust_library(
    name = "nautilus_backtest",
    srcs = glob(["src/**/*.rs"]),
    crate_features = [
        "high-precision",
        "streaming",
    ],
    crate_name = "nautilus_backtest",
    edition = "2024",
    proc_macro_deps = [
        "@nt_crates//:async-trait",
    ],
    deps = [
        "//crates/analysis:nautilus_analysis",
        "//crates/common:nautilus_common",
        "//crates/core:nautilus_core",
        "//crates/data:nautilus_data",
        "//crates/execution:nautilus_execution",
        "//crates/model:nautilus_model",
        "//crates/persistence:nautilus_persistence",
        "//crates/portfolio:nautilus_portfolio",
        "//crates/risk:nautilus_risk",
        "//crates/system:nautilus_system",
        "//crates/trading:nautilus_trading",
        "@nt_crates//:ahash",
        "@nt_crates//:anyhow",
        "@nt_crates//:bon",
        "@nt_crates//:chrono",
        "@nt_crates//:chrono-tz",
        "@nt_crates//:log",
        "@nt_crates//:rust_decimal",
        "@nt_crates//:serde_json",
        "@nt_crates//:ustr",
    ],
)
